services:
  stock-manager:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stock-manager
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      NEXT_TELEMETRY_DISABLED: "1"
